name: SeqAn2 Windows CI

on:
  push:
    branches:
      # # Push events to branches matching refs/heads/master
      # - 'master'
      # # Push events to branches matching refs/heads/develop
      # - 'develop'
  pull_request:

env:
  TZ: Europe/Berlin
  SEQAN_CONRIB_VERSION: D20200923
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17191/w_BaseKit_b_2021.1.10.2260_offline.exe
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17163/w_HPCKit_b_2021.1.10.2266_offline.exe
  WINDOWS_CPP_COMPONENTS: intel.oneapi.win.cpp-compiler

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Visual Studio 16 2019"
            os: windows-2019
            toolset: '14.28'
            msvc_ver: '16'
            build_type: Release

    steps:
      - name: Checkout SeqAn2
        uses: actions/checkout@v2
        with:
          path: seqan

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: ${{ matrix.toolset }}

      - name: Get cached SeqAn Contrib
        id: get-contrib
        uses: actions/cache@v2
        with:
          path: seqan-contrib
          key: SeqAn-Contrib-${{ env.SEQAN_CONRIB_VERSION }}

      - name: Download SeqAn Contrib
        if: steps.get-contrib.outputs.cache-hit != 'true'
        run: |
          New-Item -Name "seqan-contrib" -ItemType "directory" -Force
          cd seqan-contrib
          Invoke-WebRequest -OutFile seqan-contrib-$env:SEQAN_CONRIB_VERSION-x64.zip -TimeoutSec 30 -MaximumRetryCount 20 -RetryIntervalSec 30 http://ftp.seqan.de/contribs/seqan-contrib-$env:SEQAN_CONRIB_VERSION-x64.zip
          unzip seqan-contrib-$env:SEQAN_CONRIB_VERSION-x64.zip

      - name: Get cached python environment
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('seqan/manual/environment.yml') }}

      - name: Setup python environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: seqan
          environment-file: seqan/manual/environment.yml
          use-only-tar-bz2: true

      - name: cache install
        id: cache-install
        uses: actions/cache@v2
        with:
          path: C:\Program Files (x86)\Intel\oneAPI\compiler
          key: install-${{ env.WINDOWS_HPCKIT_URL }}-${{ env.WINDOWS_CPP_COMPONENTS }}-compiler-${{ hashFiles('**/scripts/cache_exclude_windows.sh') }}

      - name: install
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: scripts/install_windows.bat $WINDOWS_HPCKIT_URL $WINDOWS_CPP_COMPONENTS

      - name: Configure tests
        env:
          SEQAN_WIN_CONTRIB_DIRECTORY: ${{ github.workspace }}\seqan-contrib
        run: |
          "C:\Program Files (x86)\Intel\oneAPI\compiler\2021.1-beta10\env\vars.bat"
          New-Item -Name "seqan-build" -ItemType "directory" -Force
          cd seqan-build
          cmake ../seqan -G"${{ matrix.name }}" -T"Intel C++ Compiler 19.1" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DSEQAN_DISABLE_VERSION_CHECK=ON -DSEQAN_TRAVIS_BUILD:BOOL=ON

      - name: Build tests
        run: |
          cd seqan-build
          cmake --build . --config "${{ matrix.build_type }}" --parallel 2

      - name: Run tests
        run: |
          $env:Path += ";${{ github.workspace }}\seqan-contrib\seqan-contrib-$env:SEQAN_CONRIB_VERSION-x64\vs${{ matrix.msvc_ver }}\lib\"
          cd seqan-build
          ctest . -j2 -C "${{ matrix.build_type }}" --output-on-failure --timeout 120
